### ISSUE TITLE
0 reads

### ISSUE THREAD

**Issue by dhcai21** [cbg-ethz/PredictHaplo#1]
Dear authors,

I am trying to use the tool PredictHaplo to reconstruct haplotypes. But I encountered the following issue:
#######

Configuration:
  prefix = ./test/
  cons = ./HIV1.fasta
  visualization_level = 1
  FASTAreads = ./alignedReads.sam
  have_true_haplotypes = 1
  FASTAhaplos = ./haplosAligned.fasta
  do_local_Analysis = 1
After parsing the reads in file ./alignedReads.sam: average read length= nan 0
First read considered in the analysis starts at position 100000. Last read ends at position 0
There are 0 reads

#######

I used the data provided in "https://github.com/bmda-unibas/PredictHaplo". And the command is:
`predicthaplo --sam ./alignedReads.sam --reference ./HIV1.fasta --prefix ./test/ --visualization_level 1 --have_true_haplotypes 1 --true_haplotypes ./haplosAligned.fasta --do_local_Analysis 1 max_reads_in_window 5000 --entropy_threshold 0.003 --reconstruction_start 1921 --reconstruction_stop 2550 --min_qual 49 --min_length 100 --max_gap_fraction 0.025 --min_align_score_fraction 0.5 --alpha_MN_local 0.2 --min_overlap_factor 0.97 --local_window_size_factor 0.6 --cluster_number 25 --nSample 401 --include_deletions 1`

Could you please help me solve this problem? 
Thanks!
DH

**Comment by m-8k** [comment]
Thank you for reporting the issue!

As far as I can see the root of the problem is that the `master` branch of this repository hosts the version of `PredictHaplo` for paired-end reads. The test case described above appears to use example data for the original version of the application, which is incompatible. In case you want to try it out, example data for the version for paired-end reads is included in the package available [here](https://bmda.dmi.unibas.ch/software.html).
